/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora_pregunta2;

import java.awt.Button;
import java.awt.event.ActionEvent;
import java.util.Map;
import java.util.Stack;
import java.util.TreeMap;
import java.util.Vector;
import javax.swing.JButton;

/**COMPARACIÓN DE LENGUAJES
 * Primer Parcial de INF-328
 * 
 * @author Richard Pomacosi Quispe
 * 
 */
public class Frame_Calculadora extends javax.swing.JFrame {

    public String infija="";
    public static String calculo="";
    public static String posfija="";
    public Frame_Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        res = new javax.swing.JTextField();
        bpun = new javax.swing.JButton();
        bexp = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        bmas = new javax.swing.JButton();
        bigu = new javax.swing.JButton();
        bmen = new javax.swing.JButton();
        bpa = new javax.swing.JButton();
        bdiv = new javax.swing.JButton();
        bmul = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        bpc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        res2 = new javax.swing.JTextField();
        res1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("CALCULADORA");

        res.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        bpun.setBackground(new java.awt.Color(0, 51, 51));
        bpun.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bpun.setForeground(new java.awt.Color(255, 255, 255));
        bpun.setText(".");
        bpun.setName(""); // NOI18N
        bpun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpunActionPerformed(evt);
            }
        });

        bexp.setBackground(new java.awt.Color(0, 51, 51));
        bexp.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bexp.setForeground(new java.awt.Color(255, 255, 255));
        bexp.setText("^");
        bexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpunActionPerformed(evt);
            }
        });

        b0.setBackground(new java.awt.Color(0, 51, 51));
        b0.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        b0.setForeground(new java.awt.Color(255, 255, 255));
        b0.setText("0");
        b0.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                b0StateChanged(evt);
            }
        });
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpunActionPerformed(evt);
            }
        });

        b1.setBackground(new java.awt.Color(0, 51, 51));
        b1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpunActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(0, 51, 51));
        b2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 255, 255));
        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpunActionPerformed(evt);
            }
        });

        b3.setBackground(new java.awt.Color(0, 51, 51));
        b3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 255, 255));
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpunActionPerformed(evt);
            }
        });

        b4.setBackground(new java.awt.Color(0, 51, 51));
        b4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        b4.setForeground(new java.awt.Color(255, 255, 255));
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpunActionPerformed(evt);
            }
        });

        b5.setBackground(new java.awt.Color(0, 51, 51));
        b5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        b5.setForeground(new java.awt.Color(255, 255, 255));
        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpunActionPerformed(evt);
            }
        });

        b6.setBackground(new java.awt.Color(0, 51, 51));
        b6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        b6.setForeground(new java.awt.Color(255, 255, 255));
        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpunActionPerformed(evt);
            }
        });

        b7.setBackground(new java.awt.Color(0, 51, 51));
        b7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        b7.setForeground(new java.awt.Color(255, 255, 255));
        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpunActionPerformed(evt);
            }
        });

        b8.setBackground(new java.awt.Color(0, 51, 51));
        b8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        b8.setForeground(new java.awt.Color(255, 255, 255));
        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpunActionPerformed(evt);
            }
        });

        b9.setBackground(new java.awt.Color(0, 51, 51));
        b9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        b9.setForeground(new java.awt.Color(255, 255, 255));
        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpunActionPerformed(evt);
            }
        });

        bmas.setBackground(new java.awt.Color(204, 0, 102));
        bmas.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bmas.setForeground(new java.awt.Color(0, 51, 51));
        bmas.setText("+");
        bmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpunActionPerformed(evt);
            }
        });

        bigu.setBackground(new java.awt.Color(204, 0, 102));
        bigu.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bigu.setForeground(new java.awt.Color(0, 51, 51));
        bigu.setText("=");
        bigu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biguActionPerformed(evt);
            }
        });

        bmen.setBackground(new java.awt.Color(204, 0, 102));
        bmen.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bmen.setForeground(new java.awt.Color(0, 51, 51));
        bmen.setText("-");
        bmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpunActionPerformed(evt);
            }
        });

        bpa.setBackground(new java.awt.Color(0, 51, 51));
        bpa.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bpa.setForeground(new java.awt.Color(255, 255, 255));
        bpa.setText("(");
        bpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpunActionPerformed(evt);
            }
        });

        bdiv.setBackground(new java.awt.Color(204, 0, 102));
        bdiv.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bdiv.setForeground(new java.awt.Color(0, 51, 51));
        bdiv.setText("/");
        bdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpunActionPerformed(evt);
            }
        });

        bmul.setBackground(new java.awt.Color(204, 0, 102));
        bmul.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bmul.setForeground(new java.awt.Color(0, 51, 51));
        bmul.setText("*");
        bmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpunActionPerformed(evt);
            }
        });

        jButton19.setBackground(new java.awt.Color(255, 0, 0));
        jButton19.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton19.setForeground(new java.awt.Color(0, 51, 51));
        jButton19.setText("CE");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        bpc.setBackground(new java.awt.Color(0, 51, 51));
        bpc.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bpc.setForeground(new java.awt.Color(255, 255, 255));
        bpc.setText(")");
        bpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpunActionPerformed(evt);
            }
        });

        jLabel2.setText("By Richard Pomacosi Quispe");

        jLabel3.setText("Expresion infija");

        jLabel4.setText("Expresion postfija");

        res2.setBackground(new java.awt.Color(204, 204, 204));
        res2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        res2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        res2.setEnabled(false);

        res1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        res1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        res1.setEnabled(false);

        jLabel5.setText("Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(res2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(res, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bmas, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bmen, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bpun, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bexp, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bigu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(bpa, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bpc, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bmul, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(res1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(res, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(res1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bpa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bmul, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bpc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bmen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bmas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bpun, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bexp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bigu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(res2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Action Even de lo botones
    private void bpunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpunActionPerformed
    System.out.println(((JButton) evt.getSource()).getText());
    infija=infija+((JButton) evt.getSource()).getText();
    res.setText(infija);
    }//GEN-LAST:event_bpunActionPerformed

    private void biguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biguActionPerformed
                infija(res.getText().toString());
                res1.setText(calculo);
                res2.setText(posfija);
    }//GEN-LAST:event_biguActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        res1.setText("");
        res2.setText("");
        res.setText("");
        infija="";
    }//GEN-LAST:event_jButton19ActionPerformed

    private void b0StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_b0StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_b0StateChanged

  public static void infija(String in){
 
		//Expresion infija in
		
		//postfija
		Vector<String> pos=new Vector<String>();
		//parsear infija
		Vector<String> v=parsear(in);
		Stack<String> p=new Stack<String>();
		//Mapa prioridad de expresion
		Map<String, Integer> pe= new TreeMap<String, Integer>();
		pe.put("^",4 );
		pe.put("*",2 );
		pe.put("/",2 );
		pe.put("+",1 );
		pe.put("-",1 );
		pe.put("(",5 );
		//Mapa prioridad cuando esta en la pila
		Map<String, Integer> pp= new TreeMap<String, Integer>();
		pp.put("^",3 );
		pp.put("*",2 );
		pp.put("/",2 );
		pp.put("+",1 );
		pp.put("-",1 );
		pp.put("(",0 );
		try {
			
		
		for (int i = 0; i <v.size(); i++) {
			if(v.elementAt(i).equals("*")||v.elementAt(i).equals("/")||v.elementAt(i).equals("+")||v.elementAt(i).equals("-")||v.elementAt(i).equals("(")||v.elementAt(i).equals(")")||v.elementAt(i).equals("^")) {
				if(p.isEmpty()) {
					p.add(v.elementAt(i));
				}else if(v.elementAt(i).compareTo(")")!=0){
				;
					while(!p.isEmpty()&&pe.get(v.elementAt(i))<=pp.get(p.peek())) {
						pos.add(p.pop());
					}
					 p.add(v.elementAt(i));	
						}else {
							while(p.peek().compareTo("(")!=0) {
								pos.add(p.pop());
							}
							p.pop();
						}
				
			}else {
				pos.add(v.elementAt(i));
			}
		}
		while(!p.isEmpty()) {
			pos.add(p.pop());
		}
		
		System.out.println("Expresion posfija: "+pos);
                posfija=pos.toString();
		//proceso de evaluacion
		Stack<String> pev=new Stack<String>();
		Double ope1, ope2;
		for (int i = 0; i < pos.size(); i++) {
			if(pos.elementAt(i).equals("*")||pos.elementAt(i).equals("/")||pos.elementAt(i).equals("+")||pos.elementAt(i).equals("-")||pos.elementAt(i).equals("^")) {
				
				ope2=Double.parseDouble(pev.pop());
				ope1=Double.parseDouble(pev.pop());

				pev.add(calcular(ope1,ope2,pos.elementAt(i)));
			}else {
				pev.add(pos.elementAt(i));
			}
		}
		//Se muestra el resultado
		String resultado=pev.pop();
		if(!pev.empty()){
                      System.out.println("Datos incorrectos!!!!");
                      calculo="Datos Incorrectos!!!";
                }	
                else{
                    System.out.println(resultado);
                    calculo=resultado;
                }
			
		} catch (Exception e) {
			System.out.print("Datos Incorrectos");
                        calculo="Datos Incorrectos";
		}
  }
  public static String calcular(double a, double b, String x) {
	if(x.compareTo("*")==0)
		return Double.toString(a*b);
	if(x.compareTo("-")==0)
		return Double.toString(a-b);
	if(x.compareTo("/")==0)
		return Double.toString(a/b);
	if(x.compareTo("+")==0)
		return Double.toString(a+b);
	else
		return Double.toString(Math.pow(a, b));
}
 public static Vector<String> parsear(String cad){
	Vector<String>v=new Vector<String>();
	String x="";
	for (int i = 0; i <cad.length(); i++) {
			x="";
		if(cad.charAt(i)=='*'||cad.charAt(i)=='/'||cad.charAt(i)=='+'||cad.charAt(i)=='-'||cad.charAt(i)=='('||cad.charAt(i)==')'||cad.charAt(i)=='^') {
			v.add(Character.toString(cad.charAt(i)));	
		}else {
			int pos=i;
			while (pos<cad.length()&&(cad.charAt(pos)!='*'&&cad.charAt(pos)!='/'&&cad.charAt(pos)!='+'&&cad.charAt(pos)!='-'&&cad.charAt(pos)!='('&&cad.charAt(pos)!=')'&&cad.charAt(pos)!='^')) {
			
				x=x+cad.charAt(pos);
				pos++;
			}
			v.add(x);
			pos--;
			i=pos;
		}
	}
	return v;
 }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bdiv;
    private javax.swing.JButton bexp;
    private javax.swing.JButton bigu;
    private javax.swing.JButton bmas;
    private javax.swing.JButton bmen;
    private javax.swing.JButton bmul;
    private javax.swing.JButton bpa;
    private javax.swing.JButton bpc;
    private javax.swing.JButton bpun;
    private javax.swing.JButton jButton19;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField res;
    private javax.swing.JTextField res1;
    private javax.swing.JTextField res2;
    // End of variables declaration//GEN-END:variables
}
