//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_ConsumidorPregunta1.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/nombreSinDB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string nombreSinDB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/nombreSinDB", ReplyAction="*")]
        System.Threading.Tasks.Task<string> nombreSinDBAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Alumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Alumno();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Alumno", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> AlumnoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlumnoNombre", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AlumnoNombre(string ci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlumnoNombre", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> AlumnoNombreAsync(string ci);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplication_ConsumidorPregunta1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplication_ConsumidorPregunta1.ServiceReference1.WebService1Soap>, WebApplication_ConsumidorPregunta1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string nombreSinDB() {
            return base.Channel.nombreSinDB();
        }
        
        public System.Threading.Tasks.Task<string> nombreSinDBAsync() {
            return base.Channel.nombreSinDBAsync();
        }
        
        public System.Data.DataSet Alumno() {
            return base.Channel.Alumno();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> AlumnoAsync() {
            return base.Channel.AlumnoAsync();
        }
        
        public System.Data.DataSet AlumnoNombre(string ci) {
            return base.Channel.AlumnoNombre(ci);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> AlumnoNombreAsync(string ci) {
            return base.Channel.AlumnoNombreAsync(ci);
        }
    }
}
